In [2]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori as apr3, association_rules
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
spark = SparkSession.builder.getOrCreate()

In [3]:
from google.colab import files
uploaded = files.upload()

Saving rawdata.txt to rawdata (1).txt

In [4]:
f = open("rawdata.txt", "rb")
divided_teams = []
newteam = ""
#put all teams(raw data) in an array
for line in f:
    line = line.decode("utf-8")
    if (line == "\n"):
        divided_teams.append(newteam)
        newteam = ""
    else:
        newteam += line 
#put all pokemon teams in an array
final_teams = []
mons = []
for team in divided_teams:
    pokemonarray = team.split("\n")[1:7]
    for mon in range(6):
        pokemonarray[mon] = pokemonarray[mon].split(":")[0]
        #keep track of all pokemons appeared
        if pokemonarray[mon] not in mons:
            mons.append(pokemonarray[mon])
    final_teams.append(tuple(pokemonarray))

nums_of_mons = []
for team in final_teams:
    mons_there = []
    for mon in mons:
        if mon in team:
            mons_there.append(True)
        else:
            mons_there.append(False)
    nums_of_mons.append(mons_there)

data = np.array(nums_of_mons)
processed_data = pd.DataFrame(nums_of_mons, columns=mons)

# Building the model
frq_items = apr3(processed_data, min_support=0.0000001, use_colnames=True)

# Collecting the inferred rules in a dataframe
rules = association_rules(frq_items, metric="lift", min_threshold=0.0001)
rules = rules.sort_values(['confidence', 'lift'], ascending=[False, False])

In [5]:
rules["antecedents"] = rules["antecedents"].apply(list)
rules["consequents"] = rules["consequents"].apply(list)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1588,[Torkoal],[Venusaur],0.003460,0.003460,0.00346,1.000000,289.000000,0.003448,inf
1589,[Venusaur],[Torkoal],0.003460,0.003460,0.00346,1.000000,289.000000,0.003448,inf
1630,[Blastoise],[Diggersby],0.003460,0.003460,0.00346,1.000000,289.000000,0.003448,inf
1631,[Diggersby],[Blastoise],0.003460,0.003460,0.00346,1.000000,289.000000,0.003448,inf
1632,[Polteageist],[Espeon],0.003460,0.003460,0.00346,1.000000,289.000000,0.003448,inf
...,...,...,...,...,...,...,...,...,...
20257,[Landorus-Therian],"[Clefable, Buzzwole, Zeraora]",0.764706,0.024221,0.00346,0.004525,0.186813,-0.015062,0.980214
22260,[Landorus-Therian],"[Ferrothorn, Clefable, Buzzwole]",0.764706,0.024221,0.00346,0.004525,0.186813,-0.015062,0.980214
1926,[Landorus-Therian],"[Tornadus-Therian, Buzzwole]",0.764706,0.027682,0.00346,0.004525,0.163462,-0.017708,0.976738
20244,[Landorus-Therian],"[Ferrothorn, Clefable, Zeraora]",0.764706,0.027682,0.00346,0.004525,0.163462,-0.017708,0.976738
23393,[Landorus-Therian],"[Weavile, Tapu Fini, Garchomp]",0.764706,0.027682,0.00346,0.004525,0.163462,-0.017708,0.976738

In [6]:
# from pyspark.sql.types import *
# schema = StructType([
#           StructField("antecedents",ArrayType(StringType(),True),True),
#           StructField("consequents",ArrayType(StringType(),True),True),
#           StructField("antecedent support",FloatType(),True),
#           StructField("consequent support",FloatType(),True),
#           StructField("support",FloatType(),True),
#           StructField("confidence",FloatType(),True),
#           StructField("lift",FloatType(),True),
#           StructField("leverage",FloatType(),True),
#           StructField("conviction",FloatType(),True)])
df = spark.createDataFrame(rules)

In [7]:
df.createOrReplaceTempView("association_rules")
ordered_rules = spark.sql("select * from association_rules ORDER BY (confidence,lift) DESC").createOrReplaceTempView("ordered_view")

In [8]:
step_one = """
          SELECT consequents 
          FROM ordered_view 
          WHERE array_contains(antecedents,{pokemon1})
              AND cardinality(antecedents) = {arr_size}
          ORDER BY ("confidence","lift")
         """
step_two = """
          SELECT consequents 
          FROM ordered_view 
          WHERE array_contains(antecedents,{pokemon1})
              AND array_contains(antecedents,{pokemon2})
              AND cardinality(antecedents) = {arr_size}
          ORDER BY ("confidence","lift")
         """
step_three = """
          SELECT consequents 
          FROM ordered_view 
          WHERE array_contains(antecedents,{pokemon1})
              AND array_contains(antecedents,{pokemon2})
              AND array_contains(antecedents,{pokemon3})
              AND cardinality(antecedents) = {arr_size}
          ORDER BY ("confidence","lift")
         """
step_four = """
          SELECT consequents 
          FROM ordered_view 
          WHERE array_contains(antecedents,{pokemon1})
              AND array_contains(antecedents,{pokemon2})
              AND array_contains(antecedents,{pokemon3})
              AND array_contains(antecedents,{pokemon4})
              AND cardinality(antecedents) = {arr_size}
          ORDER BY ("confidence","lift")
         """
step_five = """
          SELECT consequents 
          FROM ordered_view 
          WHERE array_contains(antecedents,{pokemon1})
              AND array_contains(antecedents,{pokemon2})
              AND array_contains(antecedents,{pokemon3})
              AND array_contains(antecedents,{pokemon4})
              AND array_contains(antecedents,{pokemon5})
              AND cardinality(antecedents) = {arr_size}
          ORDER BY ("confidence","lift")
         """

In [18]:
#build a pokemon team step by step

input_pokemon = input("what are your choices,separated by comma")
final_choices = input_pokemon.split(",")

#continue running until there are 6 pokemons on the team
while(len(final_choices) < 6):
  #run the SQL queries in different scenarios
  if len(final_choices) == 1:
    suggestions = spark.sql(step_one.format(pokemon1='"%s"'%final_choices[0],arr_size=len(final_choices))).collect()
  elif len(final_choices) == 2:
    suggestions = spark.sql(step_two.format(pokemon1='"%s"'%final_choices[0],pokemon2='"%s"'%final_choices[1],arr_size=len(final_choices))).collect()
  elif len(final_choices) == 3:
    suggestions = spark.sql(step_three.format(pokemon1='"%s"'%final_choices[0],pokemon2='"%s"'%final_choices[1],pokemon3='"%s"'%final_choices[2],arr_size=len(final_choices))).collect()
  elif len(final_choices) == 4:
    suggestions = spark.sql(step_four.format(pokemon1='"%s"'%final_choices[0],pokemon2='"%s"'%final_choices[1],pokemon3='"%s"'%final_choices[2],pokemon4='"%s"'%final_choices[3],arr_size=len(final_choices))).collect()
  elif len(final_choices) == 5:
    suggestions = spark.sql(step_five.format(pokemon1='"%s"'%final_choices[0],pokemon2='"%s"'%final_choices[1],pokemon3='"%s"'%final_choices[2],pokemon4='"%s"'%final_choices[3],pokemon5='"%s"'%final_choices[4],arr_size=len(final_choices))).collect()
  cur_index = 0
  pick = suggestions[cur_index][0]

  #added the accept/reject functionality
  print("Based your current team draft, our suggestion is ")
  print(pick)
  decision = input("Do your want to accept it or try a new suggestion?(accept/reject)")
  while(decision != "accept"):
    cur_index += 1
    pick = suggestions[cur_index][0]
    print("Here is another recommendation ")
    print(pick)
    decision = input("Do your want to accept it or try a new suggestion?(accept/reject)")
  #add the recommended pokemon to the team
  if len(pick)==1:
    final_choices.append(pick[0])
  else:
    for item in pick:
      final_choices.append(item)
  print("your current draft is")
  print(final_choices)

what are your choices,separated by commaLandorus-Therian
Based your current team draft, our suggestion is
['Weavile']
Do your want to accept it or try a new suggestion?(accept/reject)reject
Here is another recommendation
['Heatran']
Do your want to accept it or try a new suggestion?(accept/reject)accept
your current draft is
['Landorus-Therian', 'Heatran']
Based your current team draft, our suggestion is
['Weavile']
Do your want to accept it or try a new suggestion?(accept/reject)reject
Here is another recommendation
['Tapu Fini']
Do your want to accept it or try a new suggestion?(accept/reject)reject
Here is another recommendation
['Kartana']
Do your want to accept it or try a new suggestion?(accept/reject)accept
your current draft is
['Landorus-Therian', 'Heatran', 'Kartana']
Based your current team draft, our suggestion is
['Weavile']
Do your want to accept it or try a new suggestion?(accept/reject)reject
Here is another recommendation
['Tapu Fini']
Do your want to accept it or try a new suggestion?(accept/reject)reject
Here is another recommendation
['Weavile', 'Tapu Fini']
Do your want to accept it or try a new suggestion?(accept/reject)accept
your current draft is
['Landorus-Therian', 'Heatran', 'Kartana', 'Weavile', 'Tapu Fini']
Based your current team draft, our suggestion is
['Zeraora']
Do your want to accept it or try a new suggestion?(accept/reject)accept
your current draft is
['Landorus-Therian', 'Heatran', 'Kartana', 'Weavile', 'Tapu Fini', 'Zeraora']

In [17]:
temp1 = spark.sql("""
          SELECT * 
          FROM ordered_view 
          WHERE array_contains(antecedents,"Landorus-Therian")
              AND array_contains(antecedents,"Heatran")
              AND array_contains(antecedents,"Kartana")
              AND cardinality(antecedents) = 3
          ORDER BY ("confidence","lift")
         """).show()

+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+------------------+
|         antecedents|         consequents| antecedent support|  consequent support|             support|         confidence|              lift|            leverage|        conviction|
+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+------------------+
|[Landorus-Therian...|           [Weavile]|0.06920415224913495| 0.44982698961937717| 0.03460207612456748|                0.5|1.1115384615384616| 0.00347218064917805|1.1003460207612457|
|[Landorus-Therian...|         [Tapu Fini]|0.06920415224913495|  0.2422145328719723|0.031141868512110725|0.44999999999999996|1.8578571428571427| 0.01437961710228565|1.3777917584145958|
|[Landorus-Therian...|[Weavile, Tapu Fini]|0.06920415224913495|  0.1245674740484429| 0.01730103806228374|               0.25|2.0069444444444446|0.008680451622945128|1.1672433679354095|
|[Landorus-Therian...|          [Clefable]|0.06920415224913495| 0.17647058823529413| 0.01730103806228374|               0.25|1.4166666666666665| 0.00508854060655404|1.0980392156862744|
|[Landorus-Therian...|[Tapu Fini, Zeraora]|0.06920415224913495| 0.03460207612456748| 0.01384083044982699|0.19999999999999998| 5.779999999999999|0.011446223105566264|1.2067474048442905|
|[Landorus-Therian...|            [Zapdos]|0.06920415224913495| 0.12110726643598616| 0.01384083044982699|0.19999999999999998|1.6514285714285712|0.005459704744914452|1.0986159169550174|
|[Landorus-Therian...|           [Zeraora]|0.06920415224913495|  0.1245674740484429| 0.01384083044982699|0.19999999999999998|1.6055555555555554| 0.00522024401048838|1.0942906574394462|
|[Landorus-Therian...|         [Dragonite]|0.06920415224913495| 0.17647058823529413| 0.01384083044982699|0.19999999999999998| 1.133333333333333|0.001628332994097292|1.0294117647058822|
|[Landorus-Therian...| [Weavile, Slowking]|0.06920415224913495|0.020761245674740483|0.010380622837370242|0.14999999999999997| 7.224999999999999|0.008943858430813807|1.1520455933238347|
|[Landorus-Therian...|[Clefable, Rotom-...|0.06920415224913495| 0.05190311418685121|0.010380622837370242|0.14999999999999997|2.8899999999999997|0.006788711820979154|1.1154081009566454|
|[Landorus-Therian...|          [Slowking]|0.06920415224913495| 0.05190311418685121|0.010380622837370242|0.14999999999999997|2.8899999999999997|0.006788711820979154|1.1154081009566454|
|[Landorus-Therian...|        [Rotom-Wash]|0.06920415224913495| 0.09342560553633218|0.010380622837370242|0.14999999999999997|1.6055555555555552|0.003915183007866284|1.0665581111337268|
|[Landorus-Therian...|[Weavile, Tapu Fi...|0.06920415224913495|0.006920415224913495|0.006920415224913495|0.09999999999999999|14.449999999999998| 0.00644149375606135|1.1034217608612071|
|[Landorus-Therian...|   [Slowbro, Zapdos]|0.06920415224913495|0.010380622837370242|0.006920415224913495|0.09999999999999999| 9.633333333333333|0.006202033021635278|1.0995770857362552|
|[Landorus-Therian...|[Moltres-Galar, T...|0.06920415224913495|0.010380622837370242|0.006920415224913495|0.09999999999999999| 9.633333333333333|0.006202033021635278|1.0995770857362552|
|[Landorus-Therian...|[Weavile, Buzzwol...|0.06920415224913495|0.010380622837370242|0.006920415224913495|0.09999999999999999| 9.633333333333333|0.006202033021635278|1.0995770857362552|
|[Landorus-Therian...| [Weavile, Buzzwole]|0.06920415224913495| 0.02422145328719723|0.006920415224913495|0.09999999999999999| 4.128571428571428|0.005244190083930987|1.0841983852364474|
|[Landorus-Therian...|     [Moltres-Galar]|0.06920415224913495| 0.02422145328719723|0.006920415224913495|0.09999999999999999| 4.128571428571428|0.005244190083930987|1.0841983852364474|
|[Landorus-Therian...|  [Weavile, Zeraora]|0.06920415224913495| 0.02422145328719723|0.006920415224913495|0.09999999999999999| 4.128571428571428|0.005244190083930987|1.0841983852364474|
|[Landorus-Therian...|[Weavile, Dragoni...|0.06920415224913495| 0.02768166089965398|0.006920415224913495|0.09999999999999999|3.6124999999999994|0.005004729349504915|1.0803537101114955|
+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+------------------+
only showing top 20 rows